
export SVN_EDITOR=vim

# local alias
alias s='source ~/.bashrc'
alias l='ls -ltrh --color'
alias ll='ls -ltrh --color'
alias grep='grep -n --color'
alias c='cd '
alias d='cd '
alias dc='cd '
alias v='vim '
alias vi='vim '
alias pwd='readlink -f .'
alias fgp='find . -type f | xargs grep --color -n '

alias L='readlink -f '
alias M='md5sum '

## personal dir
alias viv='vim ~/.vimrc'
alias vib='vim ~/.bashrc'

## WORKSPACE
alias w1='cd "/home/jovyan/butterfly/src/notebooks"'
alias w2='cd "~/Sagemaker"'
alias w3=''
alias w4=''
alias q1='nvidai-smi'
alias q2='watch --color gpustat --color'
alias q3=''
alias q4=''
alias e1=''
alias e2=''
alias e3=''
alias e4=''

## use working folder by default
[ -d /home/jovyan/butterfly/src/notebooks ] && cd /home/jovyan/butterfly/src/notebooks